import * as vscode from 'vscode';
import { exec } from 'child_process';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
    console.log('Universal File Parser is now active!');

    let disposable = vscode.commands.registerCommand('extension.parseFile', (uri: vscode.Uri) => {
        // Use the current file if no URI is provided
        const filePath = uri ? uri.fsPath : vscode.window.activeTextEditor?.document.fileName;

        if (!filePath) {
            vscode.window.showErrorMessage('No file selected for parsing.');
            return;
        }

        // 1. Identify the Python path (handles virtual environments)
        const pythonPath = path.join(context.extensionPath, '.venv', 'bin', 'python');
        const scriptPath = path.join(context.extensionPath, 'extension', 'main.py');

        vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: "Parsing File...",
            cancellable: false
        }, () => {
            return new Promise((resolve, reject) => {
                // 2. Execute Python script
                exec(`"${pythonPath}" "${scriptPath}" "${filePath}"`, (error, stdout, stderr) => {
                    if (error) {
                        vscode.window.showErrorMessage(`Error: ${stderr || error.message}`);
                        return reject();
                    }

                    try {
                        const result = JSON.parse(stdout);
                        if (result.status === 'success') {
                            // 3. Create the Webview Panel
                            const panel = vscode.window.createWebviewPanel(
                                'ufpPreview',
                                `UFP: ${path.basename(filePath)}`,
                                vscode.ViewColumn.One,
                                { enableScripts: true }
                            );

                            // 4. Set the HTML content generated by your Python HTMLGenerator
                            panel.webview.html = result.html;
                            resolve(true);
                        } else {
                            vscode.window.showErrorMessage(`Parser Error: ${result.message}`);
                            reject();
                        }
                    } catch (e) {
                        vscode.window.showErrorMessage('Failed to parse Python output.');
                        reject();
                    }
                });
            });
        });
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {}